<?php

if (function_exists('xdebug_disable'))
    xdebug_disable();

require '../src/router.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-03 at 21:49:55.
 */
class routerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var router
     */
    protected $object;

    private function addTheseRoutes() {
        $routes = array(
            'teste' => 'teste__1',
            '/index\.php\?(\d+)/' => 'index/$1',
            '/^(.+)$/'  => 'index/$1'
        );

        $this->object->addRoute($routes);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers router::addRoute
     */
    public function testAddRoute() {
        $this->object->addRoute('teste','teste__1');
        $this->assertEquals(array('teste' => 'teste__1'),$this->object->getRoutes());
    }

    public function testAddRouteArray() {
        $route = array('teste' => 'teste__1');
        $this->object->addRoute($route);
        $this->assertEquals($route,$this->object->getRoutes());
    }


    public function testMatchRouteNormal() {
        $this->addTheseRoutes();

        $this->assertEquals('teste__1',$this->object->matchRoute('teste'));
    }

    public function testMatchRouteRegex() {
        $this->addTheseRoutes();
        $this->assertEquals('index/5',$this->object->matchRoute('index.php?5'));
        $this->assertEquals('index/test1',$this->object->matchRoute('test1'));
    }

    /**
     * @covers router::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        $this->object->setControllerPath('controllers/');


    }

    /**
     * @covers router::setControllerPath
     * @todo   Implement testSetControllerPath().
     */
    public function _testSetControllerPath() {
    }

    /**
     * @covers router::getControllerPath
     * @todo   Implement testGetControllerPath().
     */
    public function _testGetControllerPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
