<?php

if (function_exists('xdebug_disable'))
    xdebug_disable();

require '../../src/Router/route.php';


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-03 at 21:49:55.
 */
class routeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Router\router
     */
    protected $object;
    
    /**
     * @var SettingsManager\settingsManager 
     */
    protected static $config = null;
    
    public static function setUpBeforeClass()
    {
        $env = getenv('ENV') ?: 'dev';
        require "../../config/config.$env.php";                
        
        //self::$config = new SettingsManager\settingsManager($routerConfig,true);                
    }

    protected function setUp() {        
        //$this->object = new Router\
    }
    
    public function testMatch() {
        $x = new Router\route('ola');
        
        $this->assertTrue($x->match('ola'));
    }
}